# PicoScenes Jekyll Theme Configuration

# Site settings
title: PicoScenes
tagline: Enabling Modern Wi-Fi ISAC Research
description: A powerful middleware for modern Wi-Fi integrated sensing and communication (Wi-Fi ISAC) research
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlight_theme: github
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
theme_color: "#0066cc"
secondary_color: "#333333"
accent_color: "#ff9900"

# Navigation
header_pages:
  - index.md
  - hardware.md
  - features_pricing.md
  - installation.md
  - scenarios.md
  - utilities.md
  - plugin.md
  - resources.md
  - troubleshooting.md

# Footer
footer_links:
  - title: GitHub
    url: https://github.com/wifisensing/PicoScenes-Issue-Tracker
  - title: Academic Paper
    url: https://doi.org/10.1109/JIOT.2021.3104666

# Additional settings
show_downloads: false
google_analytics: 
show_sidebar: true
