title: PicoScenes User Guide
description: PicoScenes User Guide

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-toc

toc:
  max_depth: 4
  min_depth: 2
  ordered: true
  class: toc-list
