title: PicoScenes Documentation
description: Comprehensive documentation for PicoScenes - A Powerful Wi-Fi Sensing Platform
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - why.md
  - features_pricing.md
  - installation.md
  - hardware.md
  - parameters.md
  - plugin.md
  - matlab.md
  - scenarios.md
  - utilities.md
  - troubleshooting.md
  - resources.md
  - credits.md

navigation:
  - title: Getting Started
    children:
      - title: Why PicoScenes
        url: /why.html
      - title: Features & Pricing
        url: /features_pricing.html
  - title: Installation & Setup
    children:
      - title: Installation Guide
        url: /installation.html
      - title: Hardware Setup
        url: /hardware.html
  - title: Documentation
    children:
      - title: Parameters Reference
        url: /parameters.html
      - title: Plugin Development
        url: /plugin.html
      - title: MATLAB Integration
        url: /matlab.html
      - title: Usage Scenarios
        url: /scenarios.html
      - title: Utilities
        url: /utilities.html
  - title: Support
    children:
      - title: Troubleshooting
        url: /troubleshooting.html
      - title: Resources
        url: /resources.html
      - title: Credits
        url: /credits.html

show_downloads: false
google_analytics:
