# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 我的网站
email: your-email@example.com
description: >- # 这意味着忽略换行符直到下一个键
  这是我的网站描述，将显示在搜索引擎结果和社交媒体分享中。
  您可以在这里添加更多详细信息。
baseurl: "" # 网站子路径，例如 /blog
url: "" # 网站的完整 URL
twitter_username: yourusername
github_username:  yourusername

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# 导航菜单项
header_pages:
  - index.md
  - features_pricing.md
  - gallery.md
  - about.md
  - why.md
  - eula.md

# 集合设置（如果需要）
# collections:
#   products:
#     output: true

# 默认设置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "网站作者"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
