title: PicoScenes Documentation
description: A Powerful Middleware for Wi-Fi Integrated Sensing and Communication Research
url: "https://github.com/wifisensing/PicoScenes-github-pages"

theme: jekyll-theme-minimal

header_pages:
  - gallery.md
  - hardware.md
  - features_pricing.md
  - installation.md
  - scenarios.md
  - matlab.md
  - plugin.md
  - utilities.md
  - ni.md
  - reshaping-wifi-isac.md
  - channels.md
  - presets.md


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag