var annotated_dup =
[
    [ "License", "namespaceLicense.html", [
      [ "Feature", "classLicense_1_1Feature.html", "classLicense_1_1Feature" ],
      [ "FeatureNaming", "classLicense_1_1FeatureNaming.html", null ],
      [ "License", "classLicense_1_1License.html", "classLicense_1_1License" ],
      [ "LicenseService", "classLicense_1_1LicenseService.html", "classLicense_1_1LicenseService" ]
    ] ],
    [ "AbstractFrontEnd", "classAbstractFrontEnd.html", "classAbstractFrontEnd" ],
    [ "AbstractHALConfiguration", "classAbstractHALConfiguration.html", "classAbstractHALConfiguration" ],
    [ "AbstractNIC", "classAbstractNIC.html", "classAbstractNIC" ],
    [ "AbstractPicoScenesPlugin", "classAbstractPicoScenesPlugin.html", "classAbstractPicoScenesPlugin" ],
    [ "AbstractSDRFrontEnd", "classAbstractSDRFrontEnd.html", "classAbstractSDRFrontEnd" ],
    [ "AsyncPipeline", "classAsyncPipeline.html", "classAsyncPipeline" ],
    [ "DSP", "classDSP.html", null ],
    [ "DSPRateTracker", "classDSPRateTracker.html", "classDSPRateTracker" ],
    [ "FIFOWaitBlocker", "classFIFOWaitBlocker.html", "classFIFOWaitBlocker" ],
    [ "FrameDumper", "classFrameDumper.html", "classFrameDumper" ],
    [ "FrontEndConfigurations", "classFrontEndConfigurations.html", "classFrontEndConfigurations" ],
    [ "FrontEndFactory", "classFrontEndFactory.html", null ],
    [ "IWL5300FrontEnd", "classIWL5300FrontEnd.html", "classIWL5300FrontEnd" ],
    [ "IWLMVMFrontEnd", "classIWLMVMFrontEnd.html", "classIWLMVMFrontEnd" ],
    [ "LoggingService", "classLoggingService.html", "classLoggingService" ],
    [ "MAC80211CSIExtractableFrontEnd", "classMAC80211CSIExtractableFrontEnd.html", "classMAC80211CSIExtractableFrontEnd" ],
    [ "MAC80211CSIExtractableNIC", "classMAC80211CSIExtractableNIC.html", "classMAC80211CSIExtractableNIC" ],
    [ "MAC80211InjectionOnlyFrontEnd", "classMAC80211InjectionOnlyFrontEnd.html", "classMAC80211InjectionOnlyFrontEnd" ],
    [ "NICPortal", "classNICPortal.html", "classNICPortal" ],
    [ "PicoScenesMessagingService", "classPicoScenesMessagingService.html", "classPicoScenesMessagingService" ],
    [ "PicoScenesPluginManager", "classPicoScenesPluginManager.html", "classPicoScenesPluginManager" ],
    [ "PicoScenesPluginWrapper", "structPicoScenesPluginWrapper.html", "structPicoScenesPluginWrapper" ],
    [ "PipelineConfig", "structPipelineConfig.html", "structPipelineConfig" ],
    [ "QCA9300FrontEnd", "classQCA9300FrontEnd.html", "classQCA9300FrontEnd" ],
    [ "SDRConnectionProfile", "structSDRConnectionProfile.html", "structSDRConnectionProfile" ],
    [ "SDRDaughterboardProfile", "structSDRDaughterboardProfile.html", "structSDRDaughterboardProfile" ],
    [ "SDRDeviceHardwareInformation", "classSDRDeviceHardwareInformation.html", "classSDRDeviceHardwareInformation" ],
    [ "SDREthernetConnectionInterface", "structSDREthernetConnectionInterface.html", "structSDREthernetConnectionInterface" ],
    [ "SDRFrontEndBasebandConfigurations", "classSDRFrontEndBasebandConfigurations.html", "classSDRFrontEndBasebandConfigurations" ],
    [ "SDRFrontEndConfigurations", "classSDRFrontEndConfigurations.html", "classSDRFrontEndConfigurations" ],
    [ "SDRFrontEndProfile", "structSDRFrontEndProfile.html", "structSDRFrontEndProfile" ],
    [ "SDRFrontEndRxStatus", "structSDRFrontEndRxStatus.html", "structSDRFrontEndRxStatus" ],
    [ "SDRFrontEndTxStatus", "structSDRFrontEndTxStatus.html", "structSDRFrontEndTxStatus" ],
    [ "SDRMainBoardInfo", "structSDRMainBoardInfo.html", "structSDRMainBoardInfo" ],
    [ "SDRNIC", "classSDRNIC.html", "classSDRNIC" ],
    [ "SDRResamplingPreset", "classSDRResamplingPreset.html", "classSDRResamplingPreset" ],
    [ "Singleton", "classSingleton.html", "classSingleton" ],
    [ "SoapySDRAbstractFrontEnd", "classSoapySDRAbstractFrontEnd.html", "classSoapySDRAbstractFrontEnd" ],
    [ "SoapySDRDeviceIdentification", "structSoapySDRDeviceIdentification.html", "structSoapySDRDeviceIdentification" ],
    [ "TaggedThreadPool", "classTaggedThreadPool.html", "classTaggedThreadPool" ],
    [ "ToFEstimationResult", "structToFEstimationResult.html", "structToFEstimationResult" ],
    [ "UDPService", "classUDPService.html", "classUDPService" ],
    [ "USRPFrontEnd", "classUSRPFrontEnd.html", "classUSRPFrontEnd" ],
    [ "VirtualSDRFrontEnd", "classVirtualSDRFrontEnd.html", "classVirtualSDRFrontEnd" ],
    [ "WebPlotService", "classWebPlotService.html", "classWebPlotService" ]
];