PicoScenes API Docs: LoggingService Class Reference
LoggingService Class Reference
#include <LoggingService.hxx>
Public Member Functions
void setLevelAll (PicoScenesLoggerLevel level)
void setLevelAll (const std::string &levelName)
void setLevel4Aspect (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level)
void setLevel4Aspect (const std::string &aspectName, const std::string &levelName)
PicoScenesLoggerLevel getLevel (PicoScenesLoggerAspect aspect) const noexcept
bool shouldLog (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level) const
template<typename... Args>
void print (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args)
template<typename... Args>
void directPrint (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args)
template<typename... Args>
void printf (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args)
template<typename... Args>
void directPrintf (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args)
void log (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, const std::string &message)
void log (PicoScenesLoggerAspect aspect, const std::exception &exception)
Static Public Member Functions
static std::shared_ptr< LoggingService > getInstance ()
Detailed Description
Definition at line 35 of file LoggingService.hxx.
Member Function Documentation
directPrint()
template<typename... Args> void LoggingService::directPrint (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args) inline
Definition at line 60 of file LoggingService.hxx.
References log(), and print().
directPrintf()
template<typename... Args> void LoggingService::directPrintf (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args) inline
Definition at line 74 of file LoggingService.hxx.
References log(), and printf().
getInstance()
static std::shared_ptr< LoggingService > LoggingService::getInstance () static
getLevel()
PicoScenesLoggerLevel LoggingService::getLevel (PicoScenesLoggerAspect aspect) const noexcept
log() [1/2]
void LoggingService::log (PicoScenesLoggerAspect aspect, const std::exception & exception)
log() [2/2]
void LoggingService::log (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, const std::string & message)
Referenced by directPrint(), directPrintf(), print(), and printf().
print()
template<typename... Args> void LoggingService::print (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args) inline
Definition at line 52 of file LoggingService.hxx.
References log(), print(), and shouldLog().
Referenced by directPrint(), and print().
printf()
template<typename... Args> void LoggingService::printf (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level, Args &&... args) inline
Definition at line 66 of file LoggingService.hxx.
References log(), printf(), and shouldLog().
Referenced by directPrintf(), and printf().
setLevel4Aspect() [1/2]
void LoggingService::setLevel4Aspect (const std::string & aspectName, const std::string & levelName)
setLevel4Aspect() [2/2]
void LoggingService::setLevel4Aspect (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level)
setLevelAll() [1/2]
void LoggingService::setLevelAll (const std::string & levelName)
setLevelAll() [2/2]
void LoggingService::setLevelAll (PicoScenesLoggerLevel level)
shouldLog()
bool LoggingService::shouldLog (PicoScenesLoggerAspect aspect, PicoScenesLoggerLevel level) const
Referenced by print(), and printf().
The documentation for this class was generated from the following file:
headers/LoggingService.hxx