PicoScenes API Docs: SDRDeviceHardwareInformation Class Reference
SDRDeviceHardwareInformation Class Reference
Class providing comprehensive hardware information for SDR devices.
#include <SDRHardwareInformation.hxx>
Public Member Functions
virtual std::vector< SDRMainBoardInfo > getAllHardwareBoards (bool refresh=false)
Get all hardware boards information.
virtual const SDRMainBoardInfo & getHardwareBoardByIndex (size_t boardIndex, bool refresh=false)
Get information for a specific board.
virtual size_t getHardwareBoardCount (bool refresh=false)
Get total number of hardware boards.
virtual const SDRMainBoardInfo & getHardwareBoardInfo (bool refresh=false)
Get main hardware board information.
virtual const std::vector< uint8_t > & getHardwareSupportedTxChannels (bool refresh=false)
Get supported Tx channels.
virtual const std::vector< uint8_t > & getHardwareSupportedRxChannels (bool refresh=false)
Get supported Rx channels.
virtual const std::vector< std::string > & getHardwareSupportedTxAntennas (uint8_t channel, bool refresh=false)
Get supported Tx antennas for a specific channel.
virtual const std::vector< std::string > & getHardwareSupportedRxAntennas (uint8_t channel, bool refresh=false)
Get supported Rx antennas for a specific channel.
virtual const std::vector< std::vector< std::string > > & getHardwareSupportedTxAntennas (bool refresh=false)
Get all supported Tx antennas.
virtual const std::vector< std::vector< std::string > > & getHardwareSupportedRxAntennas (bool refresh=false)
Get all supported Rx antennas.
virtual const std::pair< double, double > & getHardwareTxGainRange (uint8_t channel, bool refresh=false)
Get Tx gain range for a specific channel.
virtual const std::pair< double, double > & getHardwareRxGainRange (uint8_t channel, bool refresh=false)
Get Rx gain range for a specific channel.
virtual const std::vector< std::pair< double, double > > & getHardwareTxGainRanges (bool refresh=false)
Get all Tx gain ranges.
virtual const std::vector< std::pair< double, double > > & getHardwareRxGainRanges (bool refresh=false)
Get all Rx gain ranges.
virtual const std::pair< double, double > & getHardwareTxFrequencyRange (uint8_t channel, bool refresh=false)
Get Tx frequency range for a specific channel.
virtual const std::pair< double, double > & getHardwareRxFrequencyRange (uint8_t channel, bool refresh=false)
Get Rx frequency range for a specific channel.
virtual const std::vector< std::pair< double, double > > & getHardwareTxFrequencyRanges (bool refresh=false)
Get all Tx frequency ranges.
virtual const std::vector< std::pair< double, double > > & getHardwareRxFrequencyRanges (bool refresh=false)
Get all Rx frequency ranges.
virtual const std::pair< double, double > & getHardwareTxSamplingRateRange (uint8_t channel, bool refresh=false)
Get Tx sampling rate range for a specific channel.
virtual const std::pair< double, double > & getHardwareRxSamplingRateRange (uint8_t channel, bool refresh=false)
Get Rx sampling rate range for a specific channel.
virtual const std::vector< std::pair< double, double > > & getHardwareTxSamplingRateRanges (bool refresh=false)
Get all Tx sampling rate ranges.
virtual const std::vector< std::pair< double, double > > & getHardwareRxSamplingRateRanges (bool refresh=false)
Get all Rx sampling rate ranges.
virtual const std::vector< double > & getHardwareSupportedMasterClockRates (bool refresh=false)
Get supported master clock rates.
virtual const std::vector< std::string > & getHardwareSupportedClockAndTimeSources (bool refresh=false)
Get supported clock and time sources.
virtual const std::vector< std::string > & getHardwareSupportedSensors (uint8_t channel, bool refresh=false)
Get supported sensors for a specific channel.
virtual const std::vector< std::vector< std::string > > & getAllHardwareSupportedSensors (bool refresh=false)
Get all supported sensors.
virtual const std::vector< double > & getHardwareTemperatures (bool refresh=false)
Get temperature readings.
virtual bool getHardwareAGCSupport (uint8_t channel, bool refresh=false)
Get AGC support for a specific channel.
virtual const std::vector< bool > & getHardwareAGCSupport (bool refresh=false)
Get AGC support for all channels.
virtual const std::shared_ptr< SDRFrontEndProfile > & getHardwareFrontEndProfile (uint8_t channel, bool refresh=false)
Get frontend profile for a specific channel.
virtual const std::vector< std::shared_ptr< SDRFrontEndProfile > > & getHardwareFrontEndProfiles (bool refresh=false)
Get all frontend profiles.
virtual const SDRDaughterboardProfile & getHardwareDaughterboardProfile (size_t index, bool refresh=false)
Get daughterboard profile at specific index.
virtual const std::vector< SDRDaughterboardProfile > & getHardwareDaughterboardProfiles (bool refresh=false)
Get all daughterboard profiles.
virtual void refreshAllHardwareInfo ()
Refresh all hardware information.
std::string hardwareInformationSheet ()
Generate a formatted information sheet about the hardware.
virtual ~SDRDeviceHardwareInformation ()=default
Protected Member Functions
virtual void refreshHardwareInfoForSupportedChannels ()
Refresh supported channels information.
virtual void refreshHardwareInfoForSupportedAntennas ()
Refresh supported antennas information.
virtual void refreshHardwareInfoForGainRanges ()
Refresh gain ranges information.
virtual void refreshHardwareInfoForFrequencyRanges ()
Refresh frequency ranges information.
virtual void refreshHardwareInfoForSamplingRateRanges ()
Refresh sampling rate ranges information.
virtual void refreshHardwareInfoForMasterClockRates ()
Refresh master clock rates information.
virtual void refreshHardwareInfoForClockAndTimeSources ()
Refresh clock and time sources information.
virtual void refreshHardwareInfoForSensors ()
Refresh sensors information.
virtual void refreshHardwareInfoForTemperatures ()
Refresh temperature readings.
virtual void refreshHardwareInfoForAGCSupport ()
Refresh AGC support information.
virtual void refreshHardwareInfoForBoards ()
Refresh boards information.
virtual void refreshHardwareInfoForConnectionProfile ()
Refresh connection profile information.
virtual void refreshHardwareInfoForFrontEndProfiles ()
Refresh frontend profiles information.
Protected Attributes
SDRMainBoardInfo boardInfo
bool boardInfoChanged {true}
std::vector< uint8_t > supportedTxChannels {}
std::vector< uint8_t > supportedRxChannels {}
bool supportedChannelsChanged {true}
std::vector< SDRDaughterboardProfile > daughterboardProfiles {}
std::vector< std::shared_ptr< SDRFrontEndProfile > > frontendProfiles {}
bool frontendProfilesChanged {true}
std::vector< std::vector< std::string > > supportedTxAntennas {}
std::vector< std::vector< std::string > > supportedRxAntennas {}
bool supportedAntennasChanged {true}
bool supportedAntennasMapChanged {true}
std::vector< std::pair< double, double > > txGainRanges {}
std::vector< std::pair< double, double > > rxGainRanges {}
bool gainRangesChanged {true}
bool gainRangesMapChanged {true}
std::vector< std::pair< double, double > > txFrequencyRanges {}
std::vector< std::pair< double, double > > rxFrequencyRanges {}
bool frequencyRangesChanged {true}
bool frequencyRangesMapChanged {true}
std::vector< std::pair< double, double > > txSamplingRateRanges {}
std::vector< std::pair< double, double > > rxSamplingRateRanges {}
bool samplingRateRangesChanged {true}
bool samplingRateRangesMapChanged {true}
std::vector< double > supportedMasterClockRates {}
bool masterClockRatesChanged {true}
std::vector< std::string > supportedClockAndTimeSources {}
bool clockAndTimeSourcesChanged {true}
std::vector< std::vector< std::string > > supportedSensors {}
bool sensorsChanged {true}
bool sensorsMapChanged {true}
std::vector< double > temperatureReadings {}
bool temperaturesChanged {true}
std::vector< bool > agcSupport {}
bool agcSupportChanged {true}
bool agcSupportMapChanged {true}
Detailed Description
Class providing comprehensive hardware information for SDR devices.
This class provides methods to query various aspects of SDR hardware, including board information, channel capabilities, supported features, and hardware specifications. It maintains cached information that can be refreshed as needed.
Definition at line 178 of file SDRHardwareInformation.hxx.
Constructor & Destructor Documentation
~SDRDeviceHardwareInformation()
virtual SDRDeviceHardwareInformation::~SDRDeviceHardwareInformation () virtual default
Member Function Documentation
getAllHardwareBoards()
virtual std::vector< SDRMainBoardInfo > SDRDeviceHardwareInformation::getAllHardwareBoards (bool refresh = false) inline virtual
Get all hardware boards information.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of all board information
Definition at line 185 of file SDRHardwareInformation.hxx.
References boardInfo, boardInfoChanged, SDRMainBoardInfo::otherBoards, and refreshHardwareInfoForBoards().
Referenced by hardwareInformationSheet().
getAllHardwareSupportedSensors()
virtual const std::vector< std::vector< std::string > > & SDRDeviceHardwareInformation::getAllHardwareSupportedSensors (bool refresh = false) inline virtual
Get all supported sensors.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of vectors containing sensor names for each channel
Definition at line 527 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSensors(), sensorsMapChanged, and supportedSensors.
getHardwareAGCSupport() [1/2]
virtual const std::vector< bool > & SDRDeviceHardwareInformation::getHardwareAGCSupport (bool refresh = false) inline virtual
Get AGC support for all channels.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of AGC support flags for each channel
Definition at line 566 of file SDRHardwareInformation.hxx.
References agcSupport, agcSupportMapChanged, and refreshHardwareInfoForAGCSupport().
getHardwareAGCSupport() [2/2]
virtual bool SDRDeviceHardwareInformation::getHardwareAGCSupport (uint8_t channel, bool refresh = false) inline virtual
Get AGC support for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
true if AGC is supported, false otherwise
Definition at line 553 of file SDRHardwareInformation.hxx.
References agcSupport, agcSupportChanged, and refreshHardwareInfoForAGCSupport().
Referenced by hardwareInformationSheet().
getHardwareBoardByIndex()
virtual const SDRMainBoardInfo & SDRDeviceHardwareInformation::getHardwareBoardByIndex (size_t boardIndex, bool refresh = false) inline virtual
Get information for a specific board.
Parameters
boardIndex Index of the board (0 is main board)
refresh Whether to refresh the information before returning
Returns
Reference to the board information
Exceptions
std::out_of_range if boardIndex is invalid
Definition at line 202 of file SDRHardwareInformation.hxx.
References boardInfo, boardInfoChanged, SDRMainBoardInfo::otherBoards, and refreshHardwareInfoForBoards().
getHardwareBoardCount()
virtual size_t SDRDeviceHardwareInformation::getHardwareBoardCount (bool refresh = false) inline virtual
Get total number of hardware boards.
Parameters
refresh Whether to refresh the information before returning
Returns
Total number of boards
Definition at line 219 of file SDRHardwareInformation.hxx.
References boardInfo, boardInfoChanged, SDRMainBoardInfo::getTotalBoardCount(), and refreshHardwareInfoForBoards().
getHardwareBoardInfo()
virtual const SDRMainBoardInfo & SDRDeviceHardwareInformation::getHardwareBoardInfo (bool refresh = false) inline virtual
Get main hardware board information.
Parameters
refresh Whether to refresh the information before returning
Returns
Reference to main board information
Definition at line 232 of file SDRHardwareInformation.hxx.
References boardInfo, boardInfoChanged, and refreshHardwareInfoForBoards().
Referenced by hardwareInformationSheet().
getHardwareDaughterboardProfile()
virtual const SDRDaughterboardProfile & SDRDeviceHardwareInformation::getHardwareDaughterboardProfile (size_t index, bool refresh = false) inline virtual
Get daughterboard profile at specific index.
Parameters
index Daughterboard index
refresh Whether to refresh the information before returning
Returns
Reference to daughterboard profile
Definition at line 607 of file SDRHardwareInformation.hxx.
References daughterboardProfiles, frontendProfilesChanged, and refreshHardwareInfoForFrontEndProfiles().
getHardwareDaughterboardProfiles()
virtual const std::vector< SDRDaughterboardProfile > & SDRDeviceHardwareInformation::getHardwareDaughterboardProfiles (bool refresh = false) inline virtual
Get all daughterboard profiles.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of daughterboard profiles
Definition at line 620 of file SDRHardwareInformation.hxx.
References daughterboardProfiles, frontendProfilesChanged, and refreshHardwareInfoForFrontEndProfiles().
Referenced by hardwareInformationSheet().
getHardwareFrontEndProfile()
virtual const std::shared_ptr< SDRFrontEndProfile > & SDRDeviceHardwareInformation::getHardwareFrontEndProfile (uint8_t channel, bool refresh = false) inline virtual
Get frontend profile for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Shared pointer to frontend profile
Definition at line 580 of file SDRHardwareInformation.hxx.
References frontendProfiles, frontendProfilesChanged, and refreshHardwareInfoForFrontEndProfiles().
getHardwareFrontEndProfiles()
virtual const std::vector< std::shared_ptr< SDRFrontEndProfile > > & SDRDeviceHardwareInformation::getHardwareFrontEndProfiles (bool refresh = false) inline virtual
Get all frontend profiles.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of shared pointers to frontend profiles
Definition at line 593 of file SDRHardwareInformation.hxx.
References frontendProfiles, frontendProfilesChanged, and refreshHardwareInfoForFrontEndProfiles().
Referenced by hardwareInformationSheet().
getHardwareRxFrequencyRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareRxFrequencyRange (uint8_t channel, bool refresh = false) inline virtual
Get Rx frequency range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum frequency in Hz
Definition at line 394 of file SDRHardwareInformation.hxx.
References frequencyRangesChanged, refreshHardwareInfoForFrequencyRanges(), and rxFrequencyRanges.
Referenced by hardwareInformationSheet().
getHardwareRxFrequencyRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareRxFrequencyRanges (bool refresh = false) inline virtual
Get all Rx frequency ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of frequency range pairs for each channel
Definition at line 420 of file SDRHardwareInformation.hxx.
References frequencyRangesMapChanged, refreshHardwareInfoForFrequencyRanges(), and rxFrequencyRanges.
getHardwareRxGainRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareRxGainRange (uint8_t channel, bool refresh = false) inline virtual
Get Rx gain range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum gain in dB
Definition at line 340 of file SDRHardwareInformation.hxx.
References gainRangesChanged, refreshHardwareInfoForGainRanges(), and rxGainRanges.
Referenced by hardwareInformationSheet().
getHardwareRxGainRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareRxGainRanges (bool refresh = false) inline virtual
Get all Rx gain ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of gain range pairs for each channel
Definition at line 366 of file SDRHardwareInformation.hxx.
References gainRangesMapChanged, refreshHardwareInfoForGainRanges(), and rxGainRanges.
getHardwareRxSamplingRateRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareRxSamplingRateRange (uint8_t channel, bool refresh = false) inline virtual
Get Rx sampling rate range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum sampling rate in Hz
Definition at line 448 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSamplingRateRanges(), rxSamplingRateRanges, and samplingRateRangesChanged.
Referenced by hardwareInformationSheet().
getHardwareRxSamplingRateRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareRxSamplingRateRanges (bool refresh = false) inline virtual
Get all Rx sampling rate ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of sampling rate range pairs for each channel
Definition at line 474 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSamplingRateRanges(), rxSamplingRateRanges, and samplingRateRangesMapChanged.
getHardwareSupportedClockAndTimeSources()
virtual const std::vector< std::string > & SDRDeviceHardwareInformation::getHardwareSupportedClockAndTimeSources (bool refresh = false) inline virtual
Get supported clock and time sources.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of supported source names
Definition at line 500 of file SDRHardwareInformation.hxx.
References clockAndTimeSourcesChanged, refreshHardwareInfoForClockAndTimeSources(), and supportedClockAndTimeSources.
getHardwareSupportedMasterClockRates()
virtual const std::vector< double > & SDRDeviceHardwareInformation::getHardwareSupportedMasterClockRates (bool refresh = false) inline virtual
Get supported master clock rates.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of supported master clock rates in Hz
Definition at line 487 of file SDRHardwareInformation.hxx.
References masterClockRatesChanged, refreshHardwareInfoForMasterClockRates(), and supportedMasterClockRates.
Referenced by hardwareInformationSheet().
getHardwareSupportedRxAntennas() [1/2]
virtual const std::vector< std::vector< std::string > > & SDRDeviceHardwareInformation::getHardwareSupportedRxAntennas (bool refresh = false) inline virtual
Get all supported Rx antennas.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of vectors containing antenna names for each channel
Definition at line 312 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedAntennas(), supportedAntennasMapChanged, and supportedRxAntennas.
getHardwareSupportedRxAntennas() [2/2]
virtual const std::vector< std::string > & SDRDeviceHardwareInformation::getHardwareSupportedRxAntennas (uint8_t channel, bool refresh = false) inline virtual
Get supported Rx antennas for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Vector of supported antenna names
Definition at line 286 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedAntennas(), supportedAntennasChanged, and supportedRxAntennas.
Referenced by hardwareInformationSheet().
getHardwareSupportedRxChannels()
virtual const std::vector< uint8_t > & SDRDeviceHardwareInformation::getHardwareSupportedRxChannels (bool refresh = false) inline virtual
Get supported Rx channels.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of supported Rx channel numbers
Definition at line 258 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedChannels(), supportedChannelsChanged, and supportedRxChannels.
Referenced by hardwareInformationSheet().
getHardwareSupportedSensors()
virtual const std::vector< std::string > & SDRDeviceHardwareInformation::getHardwareSupportedSensors (uint8_t channel, bool refresh = false) inline virtual
Get supported sensors for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Vector of supported sensor names
Definition at line 514 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSensors(), sensorsChanged, and supportedSensors.
getHardwareSupportedTxAntennas() [1/2]
virtual const std::vector< std::vector< std::string > > & SDRDeviceHardwareInformation::getHardwareSupportedTxAntennas (bool refresh = false) inline virtual
Get all supported Tx antennas.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of vectors containing antenna names for each channel
Definition at line 299 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedAntennas(), supportedAntennasMapChanged, and supportedTxAntennas.
getHardwareSupportedTxAntennas() [2/2]
virtual const std::vector< std::string > & SDRDeviceHardwareInformation::getHardwareSupportedTxAntennas (uint8_t channel, bool refresh = false) inline virtual
Get supported Tx antennas for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Vector of supported antenna names
Definition at line 272 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedAntennas(), supportedAntennasChanged, and supportedTxAntennas.
Referenced by hardwareInformationSheet().
getHardwareSupportedTxChannels()
virtual const std::vector< uint8_t > & SDRDeviceHardwareInformation::getHardwareSupportedTxChannels (bool refresh = false) inline virtual
Get supported Tx channels.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of supported Tx channel numbers
Definition at line 245 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSupportedChannels(), supportedChannelsChanged, and supportedTxChannels.
Referenced by hardwareInformationSheet().
getHardwareTemperatures()
virtual const std::vector< double > & SDRDeviceHardwareInformation::getHardwareTemperatures (bool refresh = false) inline virtual
Get temperature readings.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of temperature values in Celsius
Definition at line 540 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForTemperatures(), temperatureReadings, and temperaturesChanged.
getHardwareTxFrequencyRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareTxFrequencyRange (uint8_t channel, bool refresh = false) inline virtual
Get Tx frequency range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum frequency in Hz
Definition at line 380 of file SDRHardwareInformation.hxx.
References frequencyRangesChanged, refreshHardwareInfoForFrequencyRanges(), and txFrequencyRanges.
Referenced by hardwareInformationSheet().
getHardwareTxFrequencyRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareTxFrequencyRanges (bool refresh = false) inline virtual
Get all Tx frequency ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of frequency range pairs for each channel
Definition at line 407 of file SDRHardwareInformation.hxx.
References frequencyRangesMapChanged, refreshHardwareInfoForFrequencyRanges(), and txFrequencyRanges.
getHardwareTxGainRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareTxGainRange (uint8_t channel, bool refresh = false) inline virtual
Get Tx gain range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum gain in dB
Definition at line 326 of file SDRHardwareInformation.hxx.
References gainRangesChanged, refreshHardwareInfoForGainRanges(), and txGainRanges.
Referenced by hardwareInformationSheet().
getHardwareTxGainRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareTxGainRanges (bool refresh = false) inline virtual
Get all Tx gain ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of gain range pairs for each channel
Definition at line 353 of file SDRHardwareInformation.hxx.
References gainRangesMapChanged, refreshHardwareInfoForGainRanges(), and txGainRanges.
getHardwareTxSamplingRateRange()
virtual const std::pair< double, double > & SDRDeviceHardwareInformation::getHardwareTxSamplingRateRange (uint8_t channel, bool refresh = false) inline virtual
Get Tx sampling rate range for a specific channel.
Parameters
channel Channel number
refresh Whether to refresh the information before returning
Returns
Pair of minimum and maximum sampling rate in Hz
Definition at line 434 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSamplingRateRanges(), samplingRateRangesChanged, and txSamplingRateRanges.
Referenced by hardwareInformationSheet().
getHardwareTxSamplingRateRanges()
virtual const std::vector< std::pair< double, double > > & SDRDeviceHardwareInformation::getHardwareTxSamplingRateRanges (bool refresh = false) inline virtual
Get all Tx sampling rate ranges.
Parameters
refresh Whether to refresh the information before returning
Returns
Vector of sampling rate range pairs for each channel
Definition at line 461 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForSamplingRateRanges(), samplingRateRangesMapChanged, and txSamplingRateRanges.
hardwareInformationSheet()
std::string SDRDeviceHardwareInformation::hardwareInformationSheet () inline
Generate a formatted information sheet about the hardware.
Returns
String containing formatted hardware information
Definition at line 651 of file SDRHardwareInformation.hxx.
References agcSupport, SDRConnectionProfile::Ethernet, frontendProfiles, getAllHardwareBoards(), getHardwareAGCSupport(), getHardwareBoardInfo(), getHardwareDaughterboardProfiles(), getHardwareFrontEndProfiles(), getHardwareRxFrequencyRange(), getHardwareRxGainRange(), getHardwareRxSamplingRateRange(), getHardwareSupportedMasterClockRates(), getHardwareSupportedRxAntennas(), getHardwareSupportedRxChannels(), getHardwareSupportedTxAntennas(), getHardwareSupportedTxChannels(), getHardwareTxFrequencyRange(), getHardwareTxGainRange(), getHardwareTxSamplingRateRange(), SDRConnectionProfile::PCIe, and SDRConnectionProfile::USB.
refreshAllHardwareInfo()
virtual void SDRDeviceHardwareInformation::refreshAllHardwareInfo () inline virtual
Refresh all hardware information.
Definition at line 631 of file SDRHardwareInformation.hxx.
References refreshHardwareInfoForAGCSupport(), refreshHardwareInfoForBoards(), refreshHardwareInfoForClockAndTimeSources(), refreshHardwareInfoForConnectionProfile(), refreshHardwareInfoForFrequencyRanges(), refreshHardwareInfoForFrontEndProfiles(), refreshHardwareInfoForGainRanges(), refreshHardwareInfoForMasterClockRates(), refreshHardwareInfoForSamplingRateRanges(), refreshHardwareInfoForSensors(), refreshHardwareInfoForSupportedAntennas(), refreshHardwareInfoForSupportedChannels(), and refreshHardwareInfoForTemperatures().
refreshHardwareInfoForAGCSupport()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForAGCSupport () inline protected virtual
Refresh AGC support information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 979 of file SDRHardwareInformation.hxx.
Referenced by getHardwareAGCSupport(), getHardwareAGCSupport(), and refreshAllHardwareInfo().
refreshHardwareInfoForBoards()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForBoards () inline protected virtual
Refresh boards information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 985 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareBoards(), getHardwareBoardByIndex(), getHardwareBoardCount(), getHardwareBoardInfo(), and refreshAllHardwareInfo().
refreshHardwareInfoForClockAndTimeSources()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForClockAndTimeSources () inline protected virtual
Refresh clock and time sources information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 961 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedClockAndTimeSources(), and refreshAllHardwareInfo().
refreshHardwareInfoForConnectionProfile()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForConnectionProfile () inline protected virtual
Refresh connection profile information.
Definition at line 991 of file SDRHardwareInformation.hxx.
Referenced by refreshAllHardwareInfo().
refreshHardwareInfoForFrequencyRanges()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForFrequencyRanges () inline protected virtual
Refresh frequency ranges information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 943 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxFrequencyRange(), getHardwareRxFrequencyRanges(), getHardwareTxFrequencyRange(), getHardwareTxFrequencyRanges(), and refreshAllHardwareInfo().
refreshHardwareInfoForFrontEndProfiles()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForFrontEndProfiles () inline protected virtual
Refresh frontend profiles information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 997 of file SDRHardwareInformation.hxx.
Referenced by getHardwareDaughterboardProfile(), getHardwareDaughterboardProfiles(), getHardwareFrontEndProfile(), getHardwareFrontEndProfiles(), and refreshAllHardwareInfo().
refreshHardwareInfoForGainRanges()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForGainRanges () inline protected virtual
Refresh gain ranges information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 937 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxGainRange(), getHardwareRxGainRanges(), getHardwareTxGainRange(), getHardwareTxGainRanges(), and refreshAllHardwareInfo().
refreshHardwareInfoForMasterClockRates()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForMasterClockRates () inline protected virtual
Refresh master clock rates information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 955 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedMasterClockRates(), and refreshAllHardwareInfo().
refreshHardwareInfoForSamplingRateRanges()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForSamplingRateRanges () inline protected virtual
Refresh sampling rate ranges information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 949 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxSamplingRateRange(), getHardwareRxSamplingRateRanges(), getHardwareTxSamplingRateRange(), getHardwareTxSamplingRateRanges(), and refreshAllHardwareInfo().
refreshHardwareInfoForSensors()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForSensors () inline protected virtual
Refresh sensors information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 967 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareSupportedSensors(), getHardwareSupportedSensors(), and refreshAllHardwareInfo().
refreshHardwareInfoForSupportedAntennas()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForSupportedAntennas () inline protected virtual
Refresh supported antennas information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 931 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxAntennas(), getHardwareSupportedRxAntennas(), getHardwareSupportedTxAntennas(), getHardwareSupportedTxAntennas(), and refreshAllHardwareInfo().
refreshHardwareInfoForSupportedChannels()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForSupportedChannels () inline protected virtual
Refresh supported channels information.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 925 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxChannels(), getHardwareSupportedTxChannels(), and refreshAllHardwareInfo().
refreshHardwareInfoForTemperatures()
virtual void SDRDeviceHardwareInformation::refreshHardwareInfoForTemperatures () inline protected virtual
Refresh temperature readings.
Reimplemented in AbstractSDRFrontEnd.
Definition at line 973 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTemperatures(), and refreshAllHardwareInfo().
Member Data Documentation
agcSupport
std::vector<bool> SDRDeviceHardwareInformation::agcSupport {} mutable protected
AGC support flags
Definition at line 1045 of file SDRHardwareInformation.hxx.
Referenced by getHardwareAGCSupport(), getHardwareAGCSupport(), and hardwareInformationSheet().
agcSupportChanged
bool SDRDeviceHardwareInformation::agcSupportChanged {true} mutable protected
Flag indicating if AGC support info needs refresh
Definition at line 1046 of file SDRHardwareInformation.hxx.
Referenced by getHardwareAGCSupport().
agcSupportMapChanged
bool SDRDeviceHardwareInformation::agcSupportMapChanged {true} mutable protected
Flag indicating if AGC support map needs refresh
Definition at line 1047 of file SDRHardwareInformation.hxx.
Referenced by getHardwareAGCSupport().
boardInfo
SDRMainBoardInfo SDRDeviceHardwareInformation::boardInfo mutable protected
Main board information
Definition at line 1001 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareBoards(), getHardwareBoardByIndex(), getHardwareBoardCount(), and getHardwareBoardInfo().
boardInfoChanged
bool SDRDeviceHardwareInformation::boardInfoChanged {true} mutable protected
Flag indicating if board info needs refresh
Definition at line 1002 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareBoards(), getHardwareBoardByIndex(), getHardwareBoardCount(), and getHardwareBoardInfo().
clockAndTimeSourcesChanged
bool SDRDeviceHardwareInformation::clockAndTimeSourcesChanged {true} mutable protected
Flag indicating if sources need refresh
Definition at line 1036 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedClockAndTimeSources().
daughterboardProfiles
std::vector<SDRDaughterboardProfile> SDRDeviceHardwareInformation::daughterboardProfiles {} mutable protected
Daughterboard profiles
Definition at line 1008 of file SDRHardwareInformation.hxx.
Referenced by getHardwareDaughterboardProfile(), and getHardwareDaughterboardProfiles().
frequencyRangesChanged
bool SDRDeviceHardwareInformation::frequencyRangesChanged {true} mutable protected
Flag indicating if frequency ranges need refresh
Definition at line 1024 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxFrequencyRange(), and getHardwareTxFrequencyRange().
frequencyRangesMapChanged
bool SDRDeviceHardwareInformation::frequencyRangesMapChanged {true} mutable protected
Flag indicating if frequency range map needs refresh
Definition at line 1025 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxFrequencyRanges(), and getHardwareTxFrequencyRanges().
frontendProfiles
std::vector<std::shared_ptr<SDRFrontEndProfile> > SDRDeviceHardwareInformation::frontendProfiles {} mutable protected
Frontend profiles
Definition at line 1009 of file SDRHardwareInformation.hxx.
Referenced by getHardwareFrontEndProfile(), getHardwareFrontEndProfiles(), and hardwareInformationSheet().
frontendProfilesChanged
bool SDRDeviceHardwareInformation::frontendProfilesChanged {true} mutable protected
Flag indicating if profiles need refresh
Definition at line 1010 of file SDRHardwareInformation.hxx.
Referenced by getHardwareDaughterboardProfile(), getHardwareDaughterboardProfiles(), getHardwareFrontEndProfile(), and getHardwareFrontEndProfiles().
gainRangesChanged
bool SDRDeviceHardwareInformation::gainRangesChanged {true} mutable protected
Flag indicating if gain ranges need refresh
Definition at line 1019 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxGainRange(), and getHardwareTxGainRange().
gainRangesMapChanged
bool SDRDeviceHardwareInformation::gainRangesMapChanged {true} mutable protected
Flag indicating if gain range map needs refresh
Definition at line 1020 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxGainRanges(), and getHardwareTxGainRanges().
masterClockRatesChanged
bool SDRDeviceHardwareInformation::masterClockRatesChanged {true} mutable protected
Flag indicating if clock rates need refresh
Definition at line 1033 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedMasterClockRates().
rxFrequencyRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::rxFrequencyRanges {} mutable protected
Rx frequency ranges
Definition at line 1023 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxFrequencyRange(), and getHardwareRxFrequencyRanges().
rxGainRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::rxGainRanges {} mutable protected
Rx gain ranges
Definition at line 1018 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxGainRange(), and getHardwareRxGainRanges().
rxSamplingRateRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::rxSamplingRateRanges {} mutable protected
Rx sampling rate ranges
Definition at line 1028 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxSamplingRateRange(), and getHardwareRxSamplingRateRanges().
samplingRateRangesChanged
bool SDRDeviceHardwareInformation::samplingRateRangesChanged {true} mutable protected
Flag indicating if sampling rate ranges need refresh
Definition at line 1029 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxSamplingRateRange(), and getHardwareTxSamplingRateRange().
samplingRateRangesMapChanged
bool SDRDeviceHardwareInformation::samplingRateRangesMapChanged {true} mutable protected
Flag indicating if sampling rate range map needs refresh
Definition at line 1030 of file SDRHardwareInformation.hxx.
Referenced by getHardwareRxSamplingRateRanges(), and getHardwareTxSamplingRateRanges().
sensorsChanged
bool SDRDeviceHardwareInformation::sensorsChanged {true} mutable protected
Flag indicating if sensor info needs refresh
Definition at line 1039 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedSensors().
sensorsMapChanged
bool SDRDeviceHardwareInformation::sensorsMapChanged {true} mutable protected
Flag indicating if sensor map needs refresh
Definition at line 1040 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareSupportedSensors().
supportedAntennasChanged
bool SDRDeviceHardwareInformation::supportedAntennasChanged {true} mutable protected
Flag indicating if antenna info needs refresh
Definition at line 1014 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxAntennas(), and getHardwareSupportedTxAntennas().
supportedAntennasMapChanged
bool SDRDeviceHardwareInformation::supportedAntennasMapChanged {true} mutable protected
Flag indicating if antenna map needs refresh
Definition at line 1015 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxAntennas(), and getHardwareSupportedTxAntennas().
supportedChannelsChanged
bool SDRDeviceHardwareInformation::supportedChannelsChanged {true} mutable protected
Flag indicating if channel info needs refresh
Definition at line 1006 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxChannels(), and getHardwareSupportedTxChannels().
supportedClockAndTimeSources
std::vector<std::string> SDRDeviceHardwareInformation::supportedClockAndTimeSources {} mutable protected
Supported clock and time sources
Definition at line 1035 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedClockAndTimeSources().
supportedMasterClockRates
std::vector<double> SDRDeviceHardwareInformation::supportedMasterClockRates {} mutable protected
Supported master clock rates
Definition at line 1032 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedMasterClockRates().
supportedRxAntennas
std::vector<std::vector<std::string> > SDRDeviceHardwareInformation::supportedRxAntennas {} mutable protected
Supported Rx antennas
Definition at line 1013 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxAntennas(), and getHardwareSupportedRxAntennas().
supportedRxChannels
std::vector<uint8_t> SDRDeviceHardwareInformation::supportedRxChannels {} mutable protected
Supported Rx channels
Definition at line 1005 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedRxChannels().
supportedSensors
std::vector<std::vector<std::string> > SDRDeviceHardwareInformation::supportedSensors {} mutable protected
Supported sensors
Definition at line 1038 of file SDRHardwareInformation.hxx.
Referenced by getAllHardwareSupportedSensors(), and getHardwareSupportedSensors().
supportedTxAntennas
std::vector<std::vector<std::string> > SDRDeviceHardwareInformation::supportedTxAntennas {} mutable protected
Supported Tx antennas
Definition at line 1012 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedTxAntennas(), and getHardwareSupportedTxAntennas().
supportedTxChannels
std::vector<uint8_t> SDRDeviceHardwareInformation::supportedTxChannels {} mutable protected
Supported Tx channels
Definition at line 1004 of file SDRHardwareInformation.hxx.
Referenced by getHardwareSupportedTxChannels().
temperatureReadings
std::vector<double> SDRDeviceHardwareInformation::temperatureReadings {} mutable protected
Temperature readings
Definition at line 1042 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTemperatures().
temperaturesChanged
bool SDRDeviceHardwareInformation::temperaturesChanged {true} mutable protected
Flag indicating if temperature readings need refresh
Definition at line 1043 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTemperatures().
txFrequencyRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::txFrequencyRanges {} mutable protected
Tx frequency ranges
Definition at line 1022 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTxFrequencyRange(), and getHardwareTxFrequencyRanges().
txGainRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::txGainRanges {} mutable protected
Tx gain ranges
Definition at line 1017 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTxGainRange(), and getHardwareTxGainRanges().
txSamplingRateRanges
std::vector<std::pair<double, double> > SDRDeviceHardwareInformation::txSamplingRateRanges {} mutable protected
Tx sampling rate ranges
Definition at line 1027 of file SDRHardwareInformation.hxx.
Referenced by getHardwareTxSamplingRateRange(), and getHardwareTxSamplingRateRanges().
The documentation for this class was generated from the following file:
headers/SDRHardwareInformation.hxx