PicoScenes API Docs: WebPlotService Class Reference
WebPlotService Class Reference abstract
提供Web绘图服务的接口类。
#include <WebPlotService.hxx>
Classes
struct PlotConfig
图表配置结构体。
Public Types
enum class PlotCategory { Performance , Platform , Plugin }
定义图表的分类。
enum class ChartType { Line , Scatter }
定义支持的图表类型。
Public Member Functions
bool plot (const PlotCategory category, const std::string &chartname, const ChartType charttype, const std::vector< std::vector< std::pair< int16_t, double > > > &data)
绘制幅度、相位数据的便利接口（使用默认配置）。
bool plot (const PlotCategory category, const std::string &chartname, const ChartType charttype, const std::vector< std::deque< std::pair< double, double > > > &data)
绘制RSS数据的便利接口（使用默认配置）。
bool plot (const PlotCategory category, const std::string &chartname, const ChartType charttype, const std::deque< std::pair< double, double > > &data)
绘制EVM、CFO、SFO数据的便利接口（使用默认配置）。
virtual bool plot (PlotCategory category, const std::string &chartname, ChartType charttype, const std::vector< std::vector< std::pair< int16_t, double > > > &data, const PlotConfig &config)=0
绘制幅度、相位数据的核心接口。
virtual bool plot (PlotCategory category, const std::string &chartname, ChartType charttype, const std::vector< std::deque< std::pair< double, double > > > &data, const PlotConfig &config)=0
绘制RSS数据的核心接口。
virtual bool plot (PlotCategory category, const std::string &chartname, ChartType charttype, const std::deque< std::pair< double, double > > &data, const PlotConfig &config)=0
绘制EVM、CFO、SFO数据的核心接口。
virtual ~WebPlotService ()=default
虚析构函数。
Static Public Member Functions
static std::shared_ptr< WebPlotService > getInstance ()
获取WebPlotService的单例实例。
Detailed Description
提供Web绘图服务的接口类。
WebPlotService 类定义了一个接口，用于通过WebSocket将数据发送到Web前端进行可视化。 它支持不同类型的数据和图表配置。该类采用单例模式实现。
Definition at line 22 of file WebPlotService.hxx.
Member Enumeration Documentation
ChartType
enum class WebPlotService::ChartType strong
定义支持的图表类型。
Enumerator
Line
折线图
Scatter
散点图
Definition at line 38 of file WebPlotService.hxx.
PlotCategory
enum class WebPlotService::PlotCategory strong
定义图表的分类。
用于将图表组织到不同的类别中，方便在Web UI中展示。
Enumerator
Performance
性能相关图表
Platform
平台相关图表
Plugin
插件相关图表
Definition at line 29 of file WebPlotService.hxx.
Constructor & Destructor Documentation
~WebPlotService()
virtual WebPlotService::~WebPlotService () virtual default
虚析构函数。
Member Function Documentation
getInstance()
static std::shared_ptr< WebPlotService > WebPlotService::getInstance () static
获取WebPlotService的单例实例。
Returns
指向WebPlotService实例的共享指针。
plot() [1/6]
bool WebPlotService::plot (const PlotCategory category, const std::string & chartname, const ChartType charttype, const std::deque< std::pair< double, double > > & data) inline
绘制EVM、CFO、SFO数据的便利接口（使用默认配置）。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 单个数据系列，是一个双端队列，包含 (x, y) 数据点，x和y均为double。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
Definition at line 93 of file WebPlotService.hxx.
References plot().
plot() [2/6]
bool WebPlotService::plot (const PlotCategory category, const std::string & chartname, const ChartType charttype, const std::vector< std::deque< std::pair< double, double > > > & data) inline
绘制RSS数据的便利接口（使用默认配置）。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 数据系列，每个系列是一个双端队列，包含 (x, y) 数据点，x和y均为double。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
Definition at line 82 of file WebPlotService.hxx.
References plot().
plot() [3/6]
bool WebPlotService::plot (const PlotCategory category, const std::string & chartname, const ChartType charttype, const std::vector< std::vector< std::pair< int16_t, double > > > & data) inline
绘制幅度、相位数据的便利接口（使用默认配置）。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 数据系列，每个系列包含 (x, y) 数据点，x为int16_t，y为double。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
Definition at line 71 of file WebPlotService.hxx.
References plot().
Referenced by plot(), plot(), and plot().
plot() [4/6]
virtual bool WebPlotService::plot (PlotCategory category, const std::string & chartname, ChartType charttype, const std::deque< std::pair< double, double > > & data, const PlotConfig & config) pure virtual
绘制EVM、CFO、SFO数据的核心接口。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 单个数据系列，是一个双端队列，包含 (x, y) 数据点，x和y均为double。
config 图表配置。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
plot() [5/6]
virtual bool WebPlotService::plot (PlotCategory category, const std::string & chartname, ChartType charttype, const std::vector< std::deque< std::pair< double, double > > > & data, const PlotConfig & config) pure virtual
绘制RSS数据的核心接口。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 数据系列，每个系列是一个双端队列，包含 (x, y) 数据点，x和y均为double。
config 图表配置。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
plot() [6/6]
virtual bool WebPlotService::plot (PlotCategory category, const std::string & chartname, ChartType charttype, const std::vector< std::vector< std::pair< int16_t, double > > > & data, const PlotConfig & config) pure virtual
绘制幅度、相位数据的核心接口。
Parameters
category 图表分类。
chartname 图表名称。
charttype 图表类型。
data 数据系列，每个系列包含 (x, y) 数据点，x为int16_t，y为double。
config 图表配置。
Returns
如果数据成功发送到WebSocket服务器，则返回true，否则返回false。
The documentation for this class was generated from the following file:
headers/WebPlotService.hxx