PicoScenes API Docs: FrontEndFactory Class Reference
FrontEndFactory Class Reference
Factory class for creating and managing front-end instances.
#include <FrontEndFactory.hxx>
Static Public Member Functions
static std::shared_ptr< AbstractFrontEnd > getFrontEndInstance (const std::string &referredInterfaceName)
Get a front-end instance for the specified interface.
template<typename FrontEndT , class = typename std::enable_if<std::is_base_of<AbstractFrontEnd, FrontEndT>::value>::type>
static std::shared_ptr< FrontEndT > getTypedFrontEndInstance (const std::string &referredInterfaceName)
Get a typed front-end instance for the specified interface.
Detailed Description
Factory class for creating and managing front-end instances.
This factory class provides static methods to create and retrieve instances of various front-end types including:
MAC80211 based NICs (QCA9300, IWL5300, IWLMVM)
USRP devices
SoapySDR devices
Virtual SDR devices
The factory implements a singleton pattern for each front-end instance, ensuring only one instance exists per interface name.
Definition at line 23 of file FrontEndFactory.hxx.
Member Function Documentation
getFrontEndInstance()
static std::shared_ptr< AbstractFrontEnd > FrontEndFactory::getFrontEndInstance (const std::string & referredInterfaceName) static
Get a front-end instance for the specified interface.
Parameters
referredInterfaceName Name or identifier of the interface
Returns
Shared pointer to AbstractFrontEnd instance
Exceptions
std::invalid_argument If the interface type is unsupported
Referenced by getTypedFrontEndInstance().
getTypedFrontEndInstance()
template<typename FrontEndT , class = typename std::enable_if<std::is_base_of<AbstractFrontEnd, FrontEndT>::value>::type> static std::shared_ptr< FrontEndT > FrontEndFactory::getTypedFrontEndInstance (const std::string & referredInterfaceName) inline static
Get a typed front-end instance for the specified interface.
Template Parameters
FrontEndT Type of front-end to create (must inherit from AbstractFrontEnd)
Parameters
referredInterfaceName Name or identifier of the interface
Returns
Shared pointer to the specified front-end type
Note
Uses SFINAE to ensure FrontEndT derives from AbstractFrontEnd
Definition at line 43 of file FrontEndFactory.hxx.
References getFrontEndInstance(), and getTypedFrontEndInstance().
Referenced by AbstractNIC::getTypedFrontEnd(), and getTypedFrontEndInstance().
The documentation for this class was generated from the following file:
headers/FrontEndFactory.hxx