PicoScenes API Docs: Intrinsics Namespace Reference
Intrinsics Namespace Reference
Functions
void * fastMemcpy (void *destAddress, const void *sourceAddress, size_t numBytes2Copy)
template<typename InputIterator , typename OutputIterator , typename = std::enable_if_t<std::is_trivially_copyable_v<typename std::iterator_traits<InputIterator>::value_type>>, typename = std::enable_if_t<std::is_same_v<typename std::iterator_traits<OutputIterator>::iterator_category, std::random_access_iterator_tag>>>
OutputIterator fastCopyN (InputIterator first, std::size_t count, OutputIterator result)
template<typename InputIterator , typename OutputIterator , typename = std::enable_if_t<std::is_trivially_copyable_v<typename std::iterator_traits<InputIterator>::value_type>>, typename = std::enable_if_t<std::is_same_v<typename std::iterator_traits<OutputIterator>::iterator_category, std::random_access_iterator_tag>>>
OutputIterator fastCopy (InputIterator first, InputIterator last, OutputIterator result)
Function Documentation
fastCopy()
template<typename InputIterator , typename OutputIterator , typename = std::enable_if_t<std::is_trivially_copyable_v<typename std::iterator_traits<InputIterator>::value_type>>, typename = std::enable_if_t<std::is_same_v<typename std::iterator_traits<OutputIterator>::iterator_category, std::random_access_iterator_tag>>> OutputIterator Intrinsics::fastCopy (InputIterator first, InputIterator last, OutputIterator result)
Definition at line 26 of file Intrinsics.hxx.
References fastCopyN().
fastCopyN()
template<typename InputIterator , typename OutputIterator , typename = std::enable_if_t<std::is_trivially_copyable_v<typename std::iterator_traits<InputIterator>::value_type>>, typename = std::enable_if_t<std::is_same_v<typename std::iterator_traits<OutputIterator>::iterator_category, std::random_access_iterator_tag>>> OutputIterator Intrinsics::fastCopyN (InputIterator first, std::size_t count, OutputIterator result)
Definition at line 17 of file Intrinsics.hxx.
References fastMemcpy().
Referenced by fastCopy(), and AbstractSDRFrontEnd::generateMultiChannelSignals().
fastMemcpy()
void * Intrinsics::fastMemcpy (void * destAddress, const void * sourceAddress, size_t numBytes2Copy)
Referenced by fastCopyN().