name: docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # choose node.js version to use
          node-version: 18
          # cache deps for pnpm
          cache: pnpm

      - name: Clean and install deps
        run: |
            rm -rf node_modules pnpm-lock.yaml
            pnpm install
      
      - name: Install deps
        run: | 
          pnpm install --frozen-lockfile
          pnpm remove @vuepress/client
          pnpm add @vuepress/client@2.0.0-rc.19 -D -E

      # run build script
      - name: Build VuePress site
        run: pnpm docs:build

      - name: Build Doxygen site
        run: |
          git clone --recursive https://x-access-token:${{ secrets.SSH_TOKEN }}@github.com/wifisensing/PicoScenes.git
          sudo apt-get install && sudo apt-get install -y doxygen graphviz
          cd PicoScenes
          doxygen ./docs/Doxyfile

      - name: Create CNAME file
        run: | 
          echo "ps.zpj.io" > dist/CNAME
          mkdir dist/html
          cp -r PicoScenes/docs/html/* dist/html
      
      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: ./dist
          cname: ps.zpj.io
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
